name: ldap_passwd_example
description: A simple example of using ldap_passwd
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.3
  ansicolor: ^1.0.2
  ldap_passwd: ^0.1.1
