name: ldap_passwd
description: A simple password utility for ldap userPassword.
version: 0.1.0
homepage: https://liudonghua123.github.io/ldap_passwd

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  convert: ^2.1.1
  crypto: ^2.1.4
  args: ^1.5.3
  ansicolor: ^1.0.2

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
