name: Build

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      PUB: pub
      DART2NATIVE: dart2native

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: ${GITHUB_REPOSITORY##*/}-linux
          - os: macOS-latest
            output-name: ${GITHUB_REPOSITORY##*/}-mac
          - os: windows-latest
            output-name: ${GITHUB_REPOSITORY##*/}-windows.exe

    steps:
      - uses: actions/checkout@v1
      - uses: DanTup/gh-actions/setup-dart@master

      - name: Change env for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "::set-env name=PUB::pub.bat"
          echo "::set-env name=DART2NATIVE::dart2native.bat"

      - name: Build
        run: |
          mkdir build
          $PUB get
          $DART2NATIVE bin/main.dart -v -o build/${{ matrix.output-name }}
        shell: bash

      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: build/*
          tags: true
          draft: false
